### ISSUE TITLE
Program self-destructs after update in specific circumstances

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#1]
### Bug Description
If the program is edited in a specific way and named a certain thing, then it manages to self-destruct if you attempt to update.

### Steps to Reproduce
1. Download version [1.4.1](https://github.com/Adam-Kay/Batch-Encoder/releases/tag/v1.4.1) (newest)
2. Edit script
3. Change internal `CurrentVersion` to `1.3`
4. Save and close
5. Run script - when prompted to update, type 'Y'
6. Update runs, then asks for confirmation to restart
7. After confirmation, program restarts and then deletes itself

### Expected behavior
The program _doesn't_ self-destruct

### Potential Cause
Since the file is still named `batch encode v1.4.1.bat` but the program's internal version is wrong, it downloads the newest current file, which also happens to be called `batch encode v1.4.1.bat`. When it then passes the `--updated-from` argument to the new file, it deletes the file the command originated from... i.e. itself.

**Comment by Artemis-Hound** [comment]
This has the potential to become critically bad if I go by this route:
> [(comment on #11)](https://github.com/Adam-Kay/Batch-Encoder/issues/11#issuecomment-1839639276_)
> * For this to work, all future releases of the tool would have to be named just `batch.encoder.bat` or `batch-encoder.bat`, with no version appended, as that would make this use of `/latest` not possible.

If all the new releases are named `batch.encoder.bat`, then they will all self-destruct upon updating as there will be nothing to differentiate the old file from the new file.
