### ISSUE TITLE
Make program updater interface directly with GitHub releases

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#11]
### Improvement Description
The current system of using the text Gist for update information is crude, and it would be better if the main program and updater were able to interface directly with the GitHub releases API to grab the latest release.

### Functionality / Design
_[As above]_

### How to implement
Using the following code to grab latest version and somehow parsing JSON information: 
``` batch
curl -L -H "Accept: application/vnd.github+json" -o _assetlist.json https://api.github.com/repos/Adam-Kay/Batch-Encoder/releases/latest
```

**Comment by Artemis-Hound** [comment]
### Addendum:
It might be a good idea to also add a changelog when the new file is downloaded.

**Comment by Artemis-Hound** [comment]
### Note:
There will need to be an intermediate update - a final release posted on the Gist that should contain the text `Please Update Again!` or something in the tool's title/startup, and that release will have the code to grab directly off GitHub. The Gist should remain up indefinitely for backwards compatibility.

**Comment by Artemis-Hound** [comment]
[This StackOverflow post](https://stackoverflow.com/a/1416247/8233240) looks promising in terms of searching through the JSON data, unless I can make the request more specific somehow.

**Comment by Artemis-Hound** [comment]
There may be no need to search through JSON data, if you use the `/latest/download/[asset-name].[ext]` that GitHub provides. 
Test command is as follows:
```batch
curl -L -o test2.bat https://github.com/Adam-Kay/Batch-Encoder/releases/latest/download/batch.encoder.v1.4.5.bat
```

#### Caveats:
- For this to work, all future releases of the tool would have to be named just `batch.encoder.bat` or `batch-encoder.bat`, with no version appended, as that would make this use of `/latest` not possible.
- Getting version information would be more difficult also this way.

**Comment by Artemis-Hound** [comment]
> [(comment)](https://github.com/Adam-Kay/Batch-Encoder/issues/11#issuecomment-1839549375)
> ### Addendum:
> It might be a good idea to also add a changelog when the new file is downloaded.

`FINDSTR` seems to be an ideal candidate for this. Remains to be seen if it can used to easily grab release information. 

Example command:
``` batch
FINDSTR /R "body" _assetlist.json
```
Result:
```
  "body": "### Changes:\r\n- Now added functionality to retain all audio streams. Output files will contain the same audio streams as the input files did."
```

**Comment by Artemis-Hound** [comment]
### Initial idea:
Use `FINDSTR` with regex to initially find the data between `"url"` and `batch.encode`, then further refine the data by using `\/asset\/` as the search word. This should give the asset URL (in theory)

**Comment by Artemis-Hound** [comment]
> ### Initial idea:
> Use `FINDSTR` with regex to initially find the data between `"url"` and `batch.encode`, then further refine the data by using `\/asset\/` as the search word. This should give the asset URL (in theory)

I hate regex. After a long time trying I finally stumbled upon [this answer](https://stackoverflow.com/a/77512949/8233240), which will give me the following as my regex statement: `(?s)url(((?!url).)*?)batch\.encoder`, which is awful and ugly but I don't really care anymore. 

**Note that this must be done in PowerShell**, ~~probably~~ in the form of the following command (edited):
```powershell
powershell -Command "`$x = Get-Content _assetlist.json -Raw; `$k = `$x | Select-String -Pattern '(?s)url(((?!url).)*?)batch\.encoder'; `$g = `$k.Matches.Value | Select-String -Pattern '`"[^`"]+?`",'; `$g.Matches.Value"
```
which gives you the result:
```
"https://api.github.com/repos/Adam-Kay/Batch-Encoder/releases/assets/138940089",
```

**Comment by Artemis-Hound** [comment]
> I hate regex.

Getting this all working took a lot of time and escaping all the special characters was not fun. See further explanation [here](https://github.com/Adam-Kay/Batch-Encoder/pull/17/commits/e2a9111e4228b63fb395d50ba2590f2bc589151e#r1423116962).

**Comment by Artemis-Hound** [comment]
> ### Addendum:
> It might be a good idea to also add a changelog when the new file is downloaded.

Now split into #19.
