### ISSUE TITLE
`batch_update.txt` is left behind if an update fails

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#13]
### Bug Description
If the auto-updater inside the program fails, a residual file (`batch_update.txt`) is left behind and not deleted.

### Steps to Reproduce
1. Edit batch encoder file ([v1.4.5](https://github.com/Adam-Kay/Batch-Encoder/releases/download/v1.4.5/batch.encoder.v1.4.5.bat) for instance)
2. Go to Line [32](https://github.com/Adam-Kay/Batch-Encoder/blob/66cf1ce/batch%20encoder.bat#L32) and mess with the Gist URL in some way to break it
3. Run batch encoder file
4. Attempt to update
5. Update will fail. File will be left behind

### Expected behavior
File should be deleted in any case.

### Potential Cause
Deletion command is bypassed when there is an error with the updater.

**Comment by Artemis-Hound** [comment]
Should investigate if [`b-e updater.bat`](https://github.com/Adam-Kay/Batch-Encoder/blob/66cf1ce/b-e%20updater.bat) does this also.

**Comment by Artemis-Hound** [comment]
> Should investigate if [`b-e updater.bat`](https://github.com/Adam-Kay/Batch-Encoder/blob/66cf1ce/b-e%20updater.bat) does this also.

It does.
