### ISSUE TITLE
Divide code into sections

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#14]
### Improvement Description
A big block of text can be hard to read, even with spaces separating certain parts

### Functionality / Design
Using comments/titles to separate out parts of the program could be quite helpful

### How to implement
You could use `rem` for comment titles, but a better-looking alternative could be to use `::[Title]`.
`::` works well provided that it's at the start of a line and not inside a code block, which titles would be.

**Comment by Artemis-Hound** [comment]
Kinda unnecessary. Most of the code is already in methods, denoted by `:[Name]`, such as 66cf1ce line [78](https://github.com/Adam-Kay/Batch-Encoder/blob/66cf1ce/batch%20encoder.bat#L78):
```batch
:Conversion
    for %%f in (.\*) do (
    ::...
```
