### ISSUE TITLE
Use colors to accentuate program

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#18]
Maybe introduce [some color](https://stackoverflow.com/a/38617204/8233240) into the program?

![image](https://github.com/Adam-Kay/Batch-Encoder/assets/10010491/8249bc0e-a858-4c5f-825f-9f949022d148)

_Originally posted by @Adam-Kay in https://github.com/Adam-Kay/Batch-Encoder/issues/12#issuecomment-1848835456_

**Comment by Artemis-Hound** [comment]
My terminal scheme is altered now, so need to consider how this will look on endpoint machine terminals.

**Comment by Artemis-Hound** [comment]
For the release notes, GitHub supports colored text via LaTeX:

`${\textsf{\color{#dddd33}\{color\}}}\$` = ${\textsf{\color{#dddd33}\{color\}}}\$

`${\textsf{\color{#ffbf00}\{A\}\color{#cc66cc}\{B\}}}\$` = ${\textsf{\color{#ffbf00}\{A\}\color{#cc66cc}\{B\}}}\$
