### ISSUE TITLE
Show changelog when updating to new version of program

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#19]
> ### Addendum:
> It might be a good idea to also add a changelog when the new file is downloaded.

_Originally posted by @Adam-Kay in https://github.com/Adam-Kay/Batch-Encoder/issues/11#issuecomment-1839549375_

**Comment by Artemis-Hound** [comment]
Given how painful doing the regex and escaping was for the v1.5.0 release (see [here](https://github.com/Adam-Kay/Batch-Encoder/issues/11#issuecomment-1849069318) and [here](https://github.com/Adam-Kay/Batch-Encoder/issues/11#issuecomment-1850874332)), I will have to see if this is even worth doing. 

If all else fails, as a stopgap I could add something like:
```
To see what changed this version, go to:
<link>
```

**Comment by Artemis-Hound** [comment]
If I need newline characters, I can use [this trick](https://stackoverflow.com/a/5642300/8233240).

**Comment by Artemis-Hound** [comment]
Using `findstr` with keyword "body", and then `%body:~11,-1%` to trim the excess. Then using the newline trick with a replace on `\r\n` will be enough to make it display properly

**Comment by Artemis-Hound** [comment]
Solved as of c339f51, looks like so:

![image](https://github.com/Adam-Kay/Batch-Encoder/assets/10010491/31c6b222-20c7-498c-a988-6f98bb5821fb)

It might change in future if it ends up feeling cluttered, but at least it's there.
