### ISSUE TITLE
Add GitHub Actions to test builds

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#21]
### Improvement Description
GitHub Actions can automate testing of builds when a new commit is pushed, which is especially useful for Pull Requests.

### Functionality / Design
Viability be investigated - see [GitHub Actions](https://docs.github.com/en/actions) page

### How to implement
Some checks of functionality, such as:
- Testing if `batch encoder.bat` correctly updates to the newest version
- Testing if `batch encoder.bat` successfully encodes one (or multiple) files
- Testing if `b-e updater.bat` correctly downloads the latest version (and removes old version)

**Comment by Artemis-Hound** [comment]
This seems to be somewhat unfeasible until launch arguments are included (#24)

**Comment by Artemis-Hound** [comment]
#24 is now resolved, work can theoretically start on this.

**Comment by Artemis-Hound** [comment]
Commit 87cee0f769ae573e7d443ece393386c5f48168d2 marks this being partially completed (basic functionality only).

To-do:
- [x] Rename job `encode` → `encoder-encode`
- [x] Add job `encoder-update`
  - Should test encoder update ability. Remove `testvideo.mp4` from [`test/`](https://github.com/Adam-Kay/Batch-Encoder/blob/main/.github/workflows/test/) (no wasted time encoding) and run:
   ```batch 
    ".\batch encoder.bat" --silent --update true --ffmpegloc ffmpeg.exe
    ```
- [x] Add job `updater-update`
  - [x] **Prerequisite:** Add `--silent` flag to b-e updater (e43b5a7)
