### ISSUE TITLE
Potential problem if the updater is not able to connect to the internet

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#22]
### Bug Description
There may be a potential issue if there is no internet connection when the updater tries to check for an update. Should investigate

[TBC BELOW]

### Potential Cause
Any potential causes of the problem.

**Comment by Artemis-Hound** [comment]
Both the old and new versions of the program _and_ the updater fail gracefully in this respect.
| Version | Program | Updater |
|--------|--------|--------|
| [v1.4.0](https://github.com/Adam-Kay/Batch-Encoder/releases/tag/v1.4.0) | ![image](https://github.com/Adam-Kay/Batch-Encoder/assets/10010491/ef8856c5-55f7-454f-ba5e-f6157698cd74) | ![image](https://github.com/Adam-Kay/Batch-Encoder/assets/10010491/c914fa1a-cbc7-4519-b57a-33990356b497) |
| [v1.5.0](https://github.com/Adam-Kay/Batch-Encoder/releases/tag/v1.5.0) | ![image](https://github.com/Adam-Kay/Batch-Encoder/assets/10010491/39a69347-7c05-4873-aed6-d379c2f2e914) | ![image](https://github.com/Adam-Kay/Batch-Encoder/assets/10010491/9410db79-bba0-4673-9892-013e03afd097) |
