### ISSUE TITLE
Program says "Finished encoding 0 files" if there are no files to encode

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#23]
### Bug Description
Program says "Finished encoding 0 files" if there are no files to encode in the folder it's in

### Steps to Reproduce
1. Make sure no other valid files are in the folder the program is run in 
2. Run program
3. Program completes and displays above message

### Expected behavior
Program should display "There were no (valid) files to encode" or something like that.

### Potential Cause
_[N/A]_

**Comment by Artemis-Hound** [comment]
Fixed as of 5174dcb.
