### ISSUE TITLE
Add launch arguments to program for quick use / testing

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#24]
### Improvement Description
The program currently asks a few questions before it gets into the encoding. This makes testing the program (i.e. via Actions as suggested in #21) or quickly launching it to go right into the main "meat" of the program not possible currently.

### Functionality / Design
Add launch arguments like `--confirm`, `--update false`, and/or <code>--ffmpegloc `[path]`</code> to answer the questions before they are asked.

**Comment by Artemis-Hound** [comment]
> Options and flags should be formatted according http://docopt.org/
In this case, the end result should be:
> - `[--silent]` : Optional
> - `--ffmpegloc <path>` : With argument
> - `--update (true|false|force)` : With limited options

_Originally posted in https://github.com/Adam-Kay/Batch-Encoder/issues/32#issuecomment-1863522504_
