### ISSUE TITLE
Program exits in rare cases where updater fails

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#31]
### Bug Description
When using `b-e updater.bat`, in the event the curl request fails during the acquisition of the main program file (in this case due to MITM on corporate networks), the program will gleefully continue and cause itself to shut down

### Steps to Reproduce
1. Use `b-e updater.bat` on a corporate network
2. Download will proceed
3. Program shows _"Download complete. The program will now clean up and restart."_
4. The program cleans up and then **exits**, as the download has not really completed due to the curl request failing (error `0x80092012`, revocation unable to check for certificate)

### Expected behavior
Download should complete and program should restart as usual

### Potential Cause
2 fixes to put in place:
1. Perform additional checks to ensure existence of downloaded file before attempting to restart
2. In case of failure, re-attempt download but with `--ssl-no-revoke` flag in curl request
    - if that fails also, take the program to `:AutoUpdateError`.

**Comment by Artemis-Hound** [comment]
This likely also happens with `batch encoder.bat` due to the nature of the problem

**Comment by Artemis-Hound** [comment]
- [x] Would close #20 when completed.

**Comment by Artemis-Hound** [comment]
About to be completed. End result:
| Standard Operation | First fail (MITM etc.) | Second Fail |
|--------|--------|--------|
| ![image](https://github.com/Adam-Kay/Batch-Encoder/assets/10010491/a12b1b8b-5a0a-4850-b283-7f92825b9901) | ![image](https://github.com/Adam-Kay/Batch-Encoder/assets/10010491/715fbd43-dd6c-4ad7-8b07-f2d0775658a6) | ![image](https://github.com/Adam-Kay/Batch-Encoder/assets/10010491/eaec3fae-ade7-4ff7-93ec-2920492f0b12) |
