### ISSUE TITLE
Consider adding force update launch argument

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#32]
### Improvement Description
Off the back of #21, the `encoder-update` action occasionally fails if the version of batch encoder being tested is concurrent with the latest release version (i.e. it does not need an update). 
_Technically_, this is not a big problem as any development being done should be a version-number up from the latest release

### How to implement
Potentially add a `--force-update` flag, or change the existing flag to be <code>--update [true|false|<b><i>force</i></b>]</code>

**Comment by Artemis-Hound** [comment]
_**¿Por qué no los dos?**_
Add the force flag, but also do a separate check for version number.
- [x] Add `force` option to `--update` flag
- [x] Add `encoder-vernum` job to [functionality.yml](https://github.com/Adam-Kay/Batch-Encoder/blob/main/.github/workflows/functionality.yml)

**Comment by Artemis-Hound** [comment]
Options and flags should be formatted according http://docopt.org/
In this case, the end result should be:
- `[--silent]` : Optional
- `--ffmpegloc <path>` : With argument
- `--update (true|false|force)` : With limited options
