### ISSUE TITLE
Error on completed encode - 1 second length difference

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#36]
### Bug Description
Got the following error after encoding a certain file:

<details><summary>Details</summary>
<p>

```
Performing file checks:
***********************

 |  Checking for output file...
- Output file exists!

 |  Checking output file length...
Input file: 00:01:17 - Output file: 00:01:18

Waiting for 0 seconds, press a key to continue ...

************************************************************

A critical error occurred. The latest file has not been modified.
```

</p>
</details> 

### Steps to Reproduce
Standard encoding workflow.

### Potential Cause
Upon closer inspection, the input file length was _1:17.997_ and the output file came to _1:18.005_ - a 7 millisecond difference. This seems to be an edge case where the encode adds a few milliseconds on, which is rare but could happen in the middle of a folder encoding, which is inconvenient.

**Comment by Artemis-Hound** [comment]
## Possible Solution:
Alter the PowerShell commands in [lines 233 to 238](https://github.com/Adam-Kay/Batch-Encoder/blob/3ac39ae9d6ce992d43b378b33cd0987480a1765a/batch%20encoder.bat#L233-L238) to instead calculate a total difference in seconds between the two clips. More than **1 second** of total difference is unreasonable, anything else is fine.

https://github.com/Adam-Kay/Batch-Encoder/blob/3ac39ae9d6ce992d43b378b33cd0987480a1765a/batch%20encoder.bat#L233-L238

### ↓
#### Gets duration of video. In future could be replaced with an `ffprobe` implementation, but for now using `ffmpeg` is preferable
```powershell
(%ffmpegloc% -i "video.mp4" 2>&1 | select-String "Duration: (.*), s").Matches.Groups[1].Value
```

#### Compares total second difference and spits out a positive integer.
```powershell
[Math]::Abs(((Get-Date %inp_len%) - (Get-Date %out_len%)).TotalSeconds)
```
