### ISSUE TITLE
Add advanced mode

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#37]
### Improvement Description
Based on the information from https://trac.ffmpeg.org/wiki/Encode/H.264#no1, it would be good to have an additional prompt that offered something along the lines of:

> Please select encoding type:
<kbd> s </kbd> - Simple encode (default options)
<kbd> a </kbd> - Advanced encoding options

The advanced options should include both an option for CRF value (quality) and a speed preset (final file size)

**Comment by Artemis-Hound** [comment]
For CRF value, reasonable ends of the scale would be between 13 and 37. The user can be provided with a 1-9 inclusive scale. To convert the user input to a CRF value, the formula will be $\mathsf{10+(usernum*3)}$, where **1** becomes **13** and **9** becomes **37**.

**Comment by Artemis-Hound** [comment]
Conveniently, there are also 9 different speed preset values so the same formula can be followed
