### ISSUE TITLE
Special characters mess with changelog displayer

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#40]
### Bug Description
Characters such as `<` and `>` mess with the changelog displayer. I have edited the notes for [Release 1.7.0](https://github.com/Adam-Kay/Batch-Encoder/releases/tag/v1.7.0) to temporarily solve the issue but these will have to be escaped.

Preferably `<kbd>` and `<code>` should have logic applied to them.

**Comment by Artemis-Hound** [comment]
Fixed in 6a12db3.
