### ISSUE TITLE
Expand deletion options via arguments

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#44]
### Improvement Description
Recycling the files is good for safety but for a confident user it may be good to have a perma-delete argument for instant disk space gains.

Also having a no delete option would be good for checking

### How to implement
- [x] Add `no-delete` or `no-recycle` option in order to retain files
- [x] Add `force-delete` or something similar option

**Comment by Artemis-Hound** [comment]
Maybe something like <code>--waste (`keep`|`recycle`[^x]|`delete`)</code>?

[^x]:Default option is `recycle`.
