### ISSUE TITLE
"Batch file cannot be found" sometimes after update

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#45]
### Bug Description
In rare cases after an update, the program will error and not continue shortly after completing the update and attempting to run cleanup.

### Steps to Reproduce
1. Have the latest version of the program (in this case the file was `batch encoder v1.7.1.bat`
2. Create a copy of the file in the same directory
3. Open a terminal in this directory
4. Run the **copy** of the program with the argument `--update force`
5. Agree to the first prompt and allow the program to force update
6. After the update is complete, press <kbd>Enter</kbd>
7. See the following message before the program exits:
```
[!] Just updated! Running cleanup…
The batch file cannot be found.
```

### Potential Cause
The program is having trouble deleting the old file after update. Maybe forcing the delete and redirecting the output using `> nul` will prevent this error from appearing and the program from exiting.

**Comment by Artemis-Hound** [comment]
Could not reproduce but added extra check on [Line 85](https://github.com/Adam-Kay/Batch-Encoder/blob/63734d2c62ce9892366936bca4b47856c6d2b89e/batch%20encoder.bat#L85)
https://github.com/Adam-Kay/Batch-Encoder/blob/63734d2c62ce9892366936bca4b47856c6d2b89e/batch%20encoder.bat#L85
