### ISSUE TITLE
Use proper semantic versioning

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#7]
Latest version released as of now is v1.4.3.1 (was a hotfix). This does not really follow standard convention - figure something else out

**Comment by Artemis-Hound** [comment]
Starting with #17, all following should follow [semver](https://semver.org/).

**Comment by Artemis-Hound** [comment]
From https://semver.org:
> **Given a version number `MAJOR`.`MINOR`.`PATCH`, increment the:**
`MAJOR` version when you make incompatible API changes
`MINOR` version when you add functionality in a backward compatible manner
`PATCH` version when you make backward compatible bug fixes
Additional labels for pre-release and build metadata are available as extensions to the `MAJOR`.`MINOR`.`PATCH` format.
