### ISSUE TITLE
Encoding dual-track audio might cause second track to be deleted

### ISSUE THREAD

**Issue by Adam-Kay** [Adam-Kay/Batch-Encoder#9]
### Bug Description
Encoding dual-audio video files might result in only the first track remaining in the resultant file.

### Steps to Reproduce
_[N/A]_

**Comment by Artemis-Hound** [comment]
Confirmed. LosslessCut shows that after the file is encoded, it is missing the second track.

Before Encode             |  After Encode
:-------------------------:|:-------------------------:
![Before](https://github.com/Adam-Kay/Batch-Encoder/assets/10010491/91fad948-5f86-4866-8f92-7e176e79322c)  |  ![After](https://github.com/Adam-Kay/Batch-Encoder/assets/10010491/98230ea0-1a5f-41f9-93af-b778298f63ee)

Potential fix: forcing ffmpeg to use **all** tracks when encoding files

**Comment by Artemis-Hound** [comment]
### Possible solution:
Based off [this post](https://stackoverflow.com/a/54616353/8233240), you can probably do:
```
ffmpeg -i in.mp4 -map 0 out.mp4
```

#### Possible issue:
It may be better to have an option to _merge_ the audio streams as opposed to keeping both separate, as video players will only play the first stream by default.

**Comment by Artemis-Hound** [comment]
> It may be better to have an option to _merge_ the audio streams as opposed to keeping both separate, as video players will only play the first stream by default.

Now split into a separate issue as #12.
